name: models
description:
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  intl: any
  flutter:
    sdk: flutter
  hive: ^2.2.3
  json_annotation: ^4.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1