name: api_source
description:
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  models:
    path: ../models
  data:
    path: ../data
  injectable: ^2.5.0
  get_it: ^8.0.3
  dio: ^5.8.0+1
  flutter_cache_manager: ^3.4.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.15
  mockito: ^5.4.2
